# Generated by Django 5.1.1 on 2024-10-27 21:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("app_year", models.IntegerField(default=2024)),
                (
                    "app_status",
                    models.CharField(
                        choices=[
                            ("A", "Accepted"),
                            ("D", "Denied"),
                            ("P", "Pending"),
                            ("I", "Incomplete"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                (
                    "health_record_status",
                    models.CharField(
                        choices=[
                            ("NC", "Not checked"),
                            ("FU", "Needs follow up"),
                            ("A", "Approved"),
                        ],
                        default="NC",
                        max_length=2,
                    ),
                ),
                (
                    "applicant_fname",
                    models.CharField(max_length=200, verbose_name="First Name"),
                ),
                (
                    "applicant_lname",
                    models.CharField(max_length=200, verbose_name="Last Name"),
                ),
                (
                    "applicant_chinese_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Chinese Name",
                    ),
                ),
                (
                    "applicant_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "parent1_fname",
                    models.CharField(
                        max_length=200, verbose_name="Primary Contact First Name"
                    ),
                ),
                (
                    "parent1_lname",
                    models.CharField(
                        max_length=200, verbose_name="Primary Contact Last Name"
                    ),
                ),
                (
                    "parent1_relationship",
                    models.CharField(
                        choices=[("F", "Father"), ("M", "Mother"), ("G", "Guardian")],
                        max_length=1,
                        verbose_name="Primary Contact Relationship",
                    ),
                ),
                (
                    "parent1_phone",
                    models.CharField(
                        max_length=15, verbose_name="Primary Contact Phone"
                    ),
                ),
                (
                    "parent1_email",
                    models.EmailField(
                        max_length=254, verbose_name="Primary Contact Email"
                    ),
                ),
                (
                    "parent1_for_POD",
                    models.BooleanField(verbose_name="Primary Contact as POD"),
                ),
                (
                    "parent2_fname",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Secondary Contact First Name",
                    ),
                ),
                (
                    "parent2_lname",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Secondary Contact Last Name",
                    ),
                ),
                (
                    "parent2_relationship",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Father"), ("M", "Mother"), ("G", "Guardian")],
                        max_length=1,
                        null=True,
                        verbose_name="Secondary Contact Relationship",
                    ),
                ),
                (
                    "parent2_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Secondary Contact Phone",
                    ),
                ),
                (
                    "parent2_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Secondary Contact Email",
                    ),
                ),
                (
                    "parent2_for_POD",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Secondary Contact as POD"
                    ),
                ),
                (
                    "interest_in_POD_lead",
                    models.BooleanField(verbose_name="Interest in POD Lead"),
                ),
                (
                    "additional_emergency_contact_fname",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Emergency Contact First Name",
                    ),
                ),
                (
                    "additional_emergency_contact_lname",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Emergency Contact Last Name",
                    ),
                ),
                (
                    "additional_emergency_contact_relationship",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Emergency Contact Relationship",
                    ),
                ),
                (
                    "additional_emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Emergency Contact Phone",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(max_length=200, verbose_name="Street"),
                ),
                ("city", models.CharField(max_length=200, verbose_name="City")),
                ("state", models.CharField(max_length=200, verbose_name="State")),
                ("zip_code", models.CharField(max_length=200, verbose_name="Zip Code")),
                ("applicant_bday", models.DateField(verbose_name="Birthday")),
                (
                    "applicant_sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "applicant_grade",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="School Grade",
                    ),
                ),
                (
                    "applicant_shirt_size",
                    models.CharField(
                        choices=[
                            ("YS", "Youth S"),
                            ("YM", "Youth M"),
                            ("YL", "Youth L"),
                            ("AS", "Adult S"),
                            ("AM", "Adult M"),
                            ("AL", "Adult L"),
                            ("AX", "Adult XL"),
                        ],
                        max_length=2,
                        verbose_name="T-Shirt Size",
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("D", "Day"),
                            ("ON", "Overnight"),
                            ("CIT", "CIT"),
                            ("C", "Counselor"),
                            ("EA", "EA"),
                        ],
                        default="ON",
                        max_length=3,
                        verbose_name="Program",
                    ),
                ),
                ("payment_received", models.BooleanField(default=False)),
                (
                    "payment_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_camp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_donation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_pod",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "allowed_pickup_persons",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("financial_aid_requested", models.BooleanField(default=False)),
                ("listing_on_weekbook", models.BooleanField(default=False)),
                (
                    "camper_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("interest_in_committee", models.BooleanField(default=False)),
                ("interest_in_wkbook_ads", models.BooleanField(default=False)),
                ("available_for_carpool", models.BooleanField(default=False)),
                ("referrals", models.CharField(blank=True, max_length=200, null=True)),
                ("heard_from", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "preferred_roommate",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "health_form_a_received",
                    models.CharField(
                        choices=[
                            ("NS", "Not Submitted"),
                            ("P", "Pending"),
                            ("A", "Approved"),
                        ],
                        default="NS",
                        max_length=10,
                    ),
                ),
                ("health_form_b_received", models.BooleanField(default=False)),
                ("medication_slip_received", models.BooleanField(default=False)),
                (
                    "parent1_cori_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "parent1_sori_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "parent1_id_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "parent2_cori_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "parent2_sori_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "parent2_id_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "camper_cori_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "camper_sori_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "camper_id_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("camp_rule_agreement", models.BooleanField(default=False)),
                ("liability_agreement", models.BooleanField(default=False)),
                (
                    "insurance_provider",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Health Insurance Provider",
                    ),
                ),
                (
                    "subscriber_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Insurance Subscriber Name",
                    ),
                ),
                (
                    "primary_physician_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Physician Name",
                    ),
                ),
                (
                    "primary_physician_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Physician Phone",
                    ),
                ),
                ("grant_hospital_permission", models.BooleanField(default=False)),
                (
                    "grant_medical_treatment_permission",
                    models.BooleanField(default=False),
                ),
                ("grant_first_aid_permission", models.BooleanField(default=False)),
                ("grant_meds_permission", models.BooleanField(default=False)),
                ("grant_bug_spray_permission", models.BooleanField(default=False)),
                ("grant_skin_treatment_permission", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                (
                    "allergies_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "initial_for_allergy_treatment",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("epi_pen_prescribed", models.BooleanField(default=False)),
                (
                    "social_emotional_concerns",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("wear_glasses", models.BooleanField(default=False)),
                ("wear_contacts", models.BooleanField(default=False)),
                ("wear_hearing_aids", models.BooleanField(default=False)),
                ("medication", models.BooleanField(default=False)),
                (
                    "medication_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "opt_out_activities",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "medical_comments",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("signature", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "group_id",
                    models.CharField(
                        blank=True, default="0", max_length=200, null=True
                    ),
                ),
                ("room_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "internal_comments",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicantHealth",
            fields=[],
            options={
                "verbose_name": "Applicant Health Info",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("necysc_app.applicant",),
        ),
    ]
