# Generated by Django 5.1.1 on 2024-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necysc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='allergies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='allergies_description',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='allowed_pickup_persons',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='available_for_carpool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='camp_rule_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='camper_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='camper_cori_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='camper_id_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='camper_sori_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='epi_pen_prescribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='financial_aid_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grant_bug_spray_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grant_first_aid_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grant_hospital_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grant_medical_treatment_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grant_meds_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grant_skin_treatment_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='health_form_a_received',
            field=models.CharField(choices=[('NS', 'Not Submitted'), ('P', 'Pending'), ('A', 'Approved')], default='NS', max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='health_form_b_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='heard_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='initial_for_allergy_treatment',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='insurance_provider',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interest_in_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interest_in_wkbook_ads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='internal_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='liability_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='listing_on_weekbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='medical_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='medication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='medication_description',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='medication_slip_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='opt_out_activities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent1_cori_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent1_id_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent1_sori_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent2_cori_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent2_id_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent2_sori_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_camp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_donation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_pod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferred_roommate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='primary_physician_name',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='primary_physician_phone',
            field=models.CharField(default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='applicant',
            name='program',
            field=models.CharField(choices=[('D', 'Day'), ('O', 'Overnight'), ('CIT', 'CIT'), ('C', 'Counselor'), ('EA', 'EA')], default='Pending', max_length=3),
        ),
        migrations.AddField(
            model_name='applicant',
            name='referrals',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='room_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='signature',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='social_emotional_concerns',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='subscriber_name',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='wear_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='wear_glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='wear_hearing_aids',
            field=models.BooleanField(default=False),
        ),
    ]
