# Generated by Django 5.1.1 on 2024-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necysc_app', '0002_applicant_allergies_applicant_allergies_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_camp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
