# Generated by Django 5.0.2 on 2024-10-15 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "necysc_app",
            "0002_applicant_allergies_applicant_allergies_description_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="user_pw",
        ),
        migrations.AddField(
            model_name="applicant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
