# Generated by Django 5.1.1 on 2024-10-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necysc_app', '0003_remove_applicant_user_email_remove_applicant_user_pw_and_more'),
        ('necysc_app', '0004_alter_applicant_allergies_description_and_more'),
    ]

    operations = [
    ]
