# Generated by Django 5.1.1 on 2024-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necysc_app', '0005_merge_20241015_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='allergies_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='group_id',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='initial_for_allergy_treatment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='medication_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_camp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='primary_physician_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='primary_physician_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='program',
            field=models.CharField(choices=[('D', 'Day'), ('ON', 'Overnight'), ('CIT', 'CIT'), ('C', 'Counselor'), ('EA', 'EA')], default='ON', max_length=3),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='subscriber_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
