# Generated by Django 5.1.1 on 2024-10-27 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("necysc_app", "0006_alter_applicant_allergies_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="additional_emergency_contact_fname",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Emergency Contact First Name",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="additional_emergency_contact_lname",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Emergency Contact Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="additional_emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Emergency Contact Phone",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="additional_emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Emergency Contact Relationship",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_bday",
            field=models.DateField(verbose_name="Birthday"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_chinese_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Chinese Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_fname",
            field=models.CharField(max_length=200, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_grade",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="School Grade",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_lname",
            field=models.CharField(max_length=200, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="applicant_shirt_size",
            field=models.CharField(
                choices=[
                    ("YS", "Youth S"),
                    ("YM", "Youth M"),
                    ("YL", "Youth L"),
                    ("AS", "Adult S"),
                    ("AM", "Adult M"),
                    ("AL", "Adult L"),
                    ("AX", "Adult XL"),
                ],
                max_length=2,
                verbose_name="T-Shirt Size",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="city",
            field=models.CharField(max_length=200, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="insurance_provider",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Health Insurance Provider",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="interest_in_POD_lead",
            field=models.BooleanField(verbose_name="Interest in POD Lead"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent1_email",
            field=models.EmailField(
                max_length=254, verbose_name="Primary Contact Email"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent1_fname",
            field=models.CharField(
                max_length=200, verbose_name="Primary Contact First Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent1_for_POD",
            field=models.BooleanField(verbose_name="Primary Contact as POD"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent1_lname",
            field=models.CharField(
                max_length=200, verbose_name="Primary Contact Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent1_phone",
            field=models.CharField(max_length=15, verbose_name="Primary Contact Phone"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent1_relationship",
            field=models.CharField(
                choices=[("F", "Father"), ("M", "Mother"), ("G", "Guardian")],
                max_length=1,
                verbose_name="Primary Contact Relationship",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent2_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Secondary Contact Email",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent2_fname",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Secondary Contact First Name",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent2_for_POD",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Secondary Contact as POD"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent2_lname",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Secondary Contact Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent2_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Secondary Contact Phone",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="parent2_relationship",
            field=models.CharField(
                blank=True,
                choices=[("F", "Father"), ("M", "Mother"), ("G", "Guardian")],
                max_length=1,
                null=True,
                verbose_name="Secondary Contact Relationship",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="primary_physician_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Physician Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="primary_physician_phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Physician Phone"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="program",
            field=models.CharField(
                choices=[
                    ("D", "Day"),
                    ("ON", "Overnight"),
                    ("CIT", "CIT"),
                    ("C", "Counselor"),
                    ("EA", "EA"),
                ],
                default="ON",
                max_length=3,
                verbose_name="Program",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="state",
            field=models.CharField(max_length=200, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="street_address",
            field=models.CharField(max_length=200, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="subscriber_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Insurance Subscriber Name",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="zip_code",
            field=models.CharField(max_length=200, verbose_name="Zip Code"),
        ),
        migrations.CreateModel(
            name="HealthInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_fname",
                    models.CharField(max_length=200, verbose_name="First Name"),
                ),
                (
                    "applicant_lname",
                    models.CharField(max_length=200, verbose_name="Last Name"),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("D", "Day"),
                            ("ON", "Overnight"),
                            ("CIT", "CIT"),
                            ("C", "Counselor"),
                            ("EA", "EA"),
                        ],
                        default="ON",
                        max_length=3,
                        verbose_name="Program",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "health_record_status",
                    models.CharField(
                        choices=[
                            ("NC", "Not checked"),
                            ("FU", "Needs follow up"),
                            ("A", "Approved"),
                        ],
                        default="NC",
                        max_length=2,
                    ),
                ),
                ("applicant_bday", models.DateField(verbose_name="Birthday")),
                (
                    "applicant_sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "health_form_a_received",
                    models.CharField(
                        choices=[
                            ("NS", "Not Submitted"),
                            ("P", "Pending"),
                            ("A", "Approved"),
                        ],
                        default="NS",
                        max_length=10,
                    ),
                ),
                ("health_form_b_received", models.BooleanField(default=False)),
                ("medication_slip_received", models.BooleanField(default=False)),
                (
                    "insurance_provider",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Health Insurance Provider",
                    ),
                ),
                (
                    "subscriber_name",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Insurance Subscriber Name",
                    ),
                ),
                (
                    "primary_physician_name",
                    models.CharField(
                        default="", max_length=200, verbose_name="Physician Name"
                    ),
                ),
                (
                    "primary_physician_phone",
                    models.CharField(
                        default="", max_length=15, verbose_name="Physician Phone"
                    ),
                ),
                ("grant_hospital_permission", models.BooleanField(default=False)),
                (
                    "grant_medical_treatment_permission",
                    models.BooleanField(default=False),
                ),
                ("grant_first_aid_permission", models.BooleanField(default=False)),
                ("grant_meds_permission", models.BooleanField(default=False)),
                ("grant_bug_spray_permission", models.BooleanField(default=False)),
                ("grant_skin_treatment_permission", models.BooleanField(default=False)),
                ("allergies", models.BooleanField(default=False)),
                ("allergies_description", models.CharField(default="", max_length=200)),
                (
                    "initial_for_allergy_treatment",
                    models.CharField(default="", max_length=200),
                ),
                ("epi_pen_prescribed", models.BooleanField(default=False)),
                (
                    "social_emotional_concerns",
                    models.CharField(default="", max_length=200),
                ),
                ("wear_glasses", models.BooleanField(default=False)),
                ("wear_contacts", models.BooleanField(default=False)),
                ("wear_hearing_aids", models.BooleanField(default=False)),
                ("medication", models.BooleanField(default=False)),
                (
                    "medication_description",
                    models.CharField(default="", max_length=200),
                ),
                ("opt_out_activities", models.CharField(default="", max_length=200)),
                ("medical_comments", models.CharField(default="", max_length=200)),
                (
                    "applicant",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="necysc_app.applicant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
