# Generated by Django 5.1.1 on 2024-10-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("necysc_app", "0007_globaldata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globaldata",
            options={
                "verbose_name": "Global Data",
                "verbose_name_plural": "Global Data",
            },
        ),
    ]
