# Generated by Django 5.1.1 on 2024-10-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "necysc_app",
            "0007_alter_applicant_additional_emergency_contact_fname_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantHealth",
            fields=[],
            options={
                "verbose_name": "Applicant Health Info",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("necysc_app.applicant",),
        ),
        migrations.DeleteModel(
            name="HealthInfo",
        ),
    ]
